server:
  port: 9201
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: concumer-ribbon
    api-b:
      path: /api-b/**
      serviceId: concumer-feign
